import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {usePrivy} from '@privy-io/react-auth';
import Form from "./components/Form"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { login } = usePrivy()

   const { ready, authenticated } = usePrivy()

    if (!ready) {
        // Do nothing while the PrivyProvider initializes with updated user state
        return <></>;
    }

  return (
    <>
      <Head>
        <title>Pinata NFT Minter</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={inter.className}>Pinata NFT Minter</h1>
        {!authenticated && ready && (
          <button className={styles.loginButton} onClick={login}>Login</button>
        )}
        {authenticated && ready && (
          <Form />
        )}
      </main>
    </>
  )
}
