import Head from 'next/head'
import { Inter } from '@next/font/google'
import Form from "./components/Form"
import Navbar from "./components/Navbar"
import Footer from "./components/Footer"
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useAccount } from 'wagmi'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { isConnected } = useAccount()

  return (
    <>
      <Head>
        <title>Pinata NFT Minter</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`flex flex-col justify-between min-h-screen h-full bg-hero-bubbles bg-cover`}>
        <div className="my-4 max-w-screen-xl flex flex-col justify-center mx-auto w-full">
          <Navbar />
        </div>

        <div className="my-4 max-w-screen-xl flex flex-col justify-center items-center h-full mx-auto gap-6">
          <h1 className="font-agrandir text-7xl font-bold mb-9">Pinata NFT Minter</h1>
          {!isConnected && (
            <ConnectButton />
          )}
          {isConnected && (
            <Form />
          )}

        </div>
        <Footer />
      </main>
    </>
  )
}
